### ISSUE TITLE
Why does Travis.genkeys take a module instead of strings?

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaDocs/DocumenterTools.jl#19]
@mortenpi, I read the docs for Documenter.jl [SSH-deploy-keys](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1) and thought it was odd for `DocumenterTools.Travis.genkeys` to require the module in order to generate the keys.

For example `DocumenterTools.Travis.genkeys(MyModule)` requires that MyModule be installed in development mode. Why does `genkeys` require the module to be loaded since at the end of the day it boils down to a call to `genkeys(; user=user, repo=repo)` why wouldn't I just call that directly?

`genkeys("$GITHUB_USER", "$REPO_PATH")` is easy enough for me to use. 

Doesn't the `genkeys(MyModule)` version force your package to require DocumenterTools.jl just for the one time you generate the keys? 

Is there something I am missing?

**Comment by mortenpi** [comment]
This is mainly an artifact of the old API really. It used to be that Documenter had to put a file into your repository directory with the key (`.documenter.enc`; now this is the `DOCUMENTER_KEY` environment variable) and so it needed to know the path to the local repo. It used `Pkg.dir("PackageName")` to figure it out.

When updating to 1.0, we kept the old API, because it also prints the exact URLs, making things a bit easier for the user. The only thing is that in 1.0, `pathof(::Module)` is the only way to determine the path of the repo. And to figure out the Git URL automatically, it needs to be checked out as a Git repo (i.e. dev mode). Hence the `genkeys(::Module)` API as it is today.

All that said, I think that on the page you linked we should probably recommend the `genkeys(; user=user, repo=repo)` API and just mention the `::Module` version as a shorthand you can use if your package is already in dev-mode and imported.

> Doesn't the `genkeys(MyModule)` version force your package to require DocumenterTools.jl just for the one time you generate the keys?

Not sure what you mean. You never have to have DocumenterTools in as a dependency of your package. You would just have it in your global environment.

**Comment by mortenpi** [comment]
Closed by JuliaDocs/Documenter.jl#913
