### ISSUE TITLE
ssh-keygen as a jll

### ISSUE THREAD

**Issue by Nosferican** [JuliaDocs/DocumenterTools.jl#36]
Currently the package assumes access to `Sys.which` and it implies access to the `PATH` environmental variable which is not always accessible to the environment (e.g., Visual Studio Code on OSX).
The better way to implement it would be to have `ssh-keygen` as a jll.

**Comment by mortenpi** [comment]
Actually, currently we're using the `which` (or `where` on Windows) binary to check for `ssh-keygen`. Switching to `Sys.which` would already be an improvement.

But yes, ideally we'd just pull in `ssh-keygen` as a binary dependency, so that we could guarantee that it would always work. I believe this would require a build of OpenSSH, which I did not see it in Yggdrasil though.

Also, moved this issue to the DocumenterTools repo.

**Comment by Nosferican** [comment]
Sounds good. Sorry for opening the issue at the wrong repo... I should go to bed already.

**Comment by aminya** [comment]
We should transfer this to https://github.com/aminya/Keygen.jl
