### ISSUE TITLE
Instructions for installing DOCUMENTER_KEY on GitHub are out of date

### ISSUE THREAD

**Issue by MarkNahabedian** [JuliaDocs/DocumenterTools.jl#84]
`DocumenterTools.genkeys()` produces output like

>┌ Info: Add the key below as a new 'Deploy key' on GitHub (https://github.com/$USER/$REPO/settings/keys) with read and write access.
>└ The 'Title' field can be left empty as GitHub can infer it from the key comment.
>
>*public key*
>
>[ Info: Add a secure environment variable named 'DOCUMENTER_KEY' (to https://github.com/$USER/$REPO/settings/secrets if you deploy using GitHub Actions) with value:
>
>*private key*

Unfortunately, these instructions no longer match GitHub's current web interface.  Neither of the URLs are valid.  The terminology in the info no longer matches what appears in the GitHub repository settings pages.

Please update the info.

**Comment by mortenpi** [comment]
The first URL seems to be valid still. The second one does redirect to a new one. Happy to review a PR to improve to docs though.

**Comment by abelsiqueira** [comment]
The links work for me. It does assume that you have access to those pages, which might not be case if, e.g., the package does not exists, or you not a member of the org.
The wording of the private key could be improved, I had users confused because GitHub did make changes to that. I will make a PR now.
